/*
 * gang-comisiones
 * COPYLEFT 2025
 * Ingenieria Informatica Yupay SACS
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */
package com.yupay.gangcomisiones.export;

import com.yupay.gangcomisiones.model.GlobalConfig;
import com.yupay.gangcomisiones.model.Transaction;

import java.util.concurrent.CompletableFuture;

/**
 * Public controller for exporting a {@link Transaction} as bytes in the selected {@link OutputType}.
 * This component performs no external I/O (no file/network). It only returns the generated bytes
 * wrapped in a {@link CompletableFuture}.
 * <br/>
 * Signature: {@code export(Transaction tx, OutputType type, GlobalConfig cfg)} -&gt; {@code CompletableFuture<byte[]>}.
 *
 * @author InfoYupay SACS
 * @version 1.0
 */
public interface TicketExporter {
    /**
     * Exports the given transaction as bytes for the specified output type.
     *
     * @param tx   the transaction to render
     * @param type output type to produce
     * @param cfg  global configuration providing business metadata
     * @return a future resolving to the exported bytes (never null)
     */
    CompletableFuture<byte[]> export(Transaction tx, OutputType type, GlobalConfig cfg);
}
